/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jamiexu_app_J */

#ifndef _Included_com_jamiexu_app_J
#define _Included_com_jamiexu_app_J
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jamiexu_app_J
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jamiexu_app_J_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
