/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../../AndroidSDK/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_jamiexu_app_J */

#ifndef _Included_com_jamiexu_app_J
#define _Included_com_jamiexu_app_J
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jamiexu_app_J
 * Method:    init
 * Signature: (Landroid/content/Context;)V
 */



JNIEXPORT void JNICALL
Java_com_jamiexu_app_J_init
        (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL
Java_com_jamiexu_app_J_cf(JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL
Java_com_jamiexu_app_J_i(JNIEnv *env, jclass clazz,jobject);


#ifdef __cplusplus
}
#endif
#endif
